# Generated by Django 3.0.8 on 2020-07-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200713_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='extension',
            field=models.CharField(default='.mp4', max_length=10),
            preserve_default=False,
        ),
    ]
