# Generated by Django 3.0.8 on 2020-07-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200714_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
