# Generated by Django 3.0.8 on 2020-07-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_film_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
