# Generated by Django 3.0.8 on 2020-07-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200715_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='watched_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
