# Generated by Django 3.0.8 on 2020-07-15 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_film_watched_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastViewed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
