# Generated by Django 3.0.8 on 2020-07-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lastviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='csfd_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='csfd_rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
