# Generated by Django 3.0.8 on 2020-07-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200716_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filmviewed',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
